### ISSUE TITLE
Unable to get ros-noetic-amcl and ros-noetic-base-local-planner packages

### ISSUE THREAD

**Issue by codingCoffee** [ros-noetic-arch/ros-noetic-turtlebot3#1]
```
➜ yay -S ros-noetic-turtlebot3
 -> Could not find all required packages:
        ros-noetic-amcl (Wanted by: ros-noetic-turtlebot3 -> ros-noetic-turtlebot3-navigation)
        ros-noetic-base-local-planner (Wanted by: ros-noetic-turtlebot3 -> ros-noetic-turtlebot3-navigation -> ros-noetic-move-base)
        ros-noetic-base-local-planner (Wanted by: ros-noetic-turtlebot3 -> ros-noetic-turtlebot3-navigation -> ros-noetic-move-base -> ros-noetic-rotate-recovery)
```

So as the title suggests, installation for the `ros-noetic-turtlebot3` meta package is failing because the packages for `ros-noetic-amcl` and `ros-noetic-base-local-planner` are not present on AUR. 
One quick fix is to remove `ros-noetic-amcl` and `ros-noetic-base-local-planner` as dependencies from 
- [ros-noetic-turtlebot3-navigation/blob/master/PKGBUILD#L22](https://github.com/ros-noetic-arch/ros-noetic-turtlebot3-navigation/blob/61ecce9aee693ddbe0966adaff50cc1c3c3697ef/PKGBUILD#L22)
- ros-noetic-base-local-planner
- ros-noetic-rotate-recovery

But I would rather like to help on creating the `ros-noetic-amcl` and `ros-noetic-base-local-planner` packages themselves, since I noticed you have the repos for [ros-noetic-amcl](https://github.com/ros-noetic-arch/ros-noetic-amcl) and [ros-noetic-base-local-planner](https://github.com/ros-noetic-arch/ros-noetic-base-local-planner) but they are basically empty.

I'm a complete beginner at ROS, with almost no knowledge, but have been an Arch user for quite a while. It would be really helpful if you could help guide me how to go about it.

**Comment by acxz** [comment]
Hey @codingCoffee nice to have more ROS users on Arch.

> But I would rather like to help on creating the ros-noetic-amcl and ros-noetic-base-local-planner packages themselves, since I noticed you have the repos for ros-noetic-amcl and ros-noetic-base-local-planner but they are basically empty.

This is indeed the way to go. Basically you could submit working PKGBUILDs as a pull request on those repos.

**Comment by acxz** [comment]
I went ahead and added the pkgbuilds from melodic and updated them for noetic. Thought it would just be faster if I did it real quick, thx for reporting the issue.
In the future, if the PKGBUILD doesn't exist then you can take a look at existing packages and change the relevant fields. You can also contribute by updating PKGBUILDs.
